source: app
destination: app/_site

# Site settings
title: Carlo Rodriguez
subtitle: Full Stack & Mobile Developer
description: > # this means to ignore newlines until "baseurl:"
  This is a material design personal site.

author: Carlo Eduardo Rodriguez Espino
author_website:
email: carloerodriguez@gmail.com

baseurl: ""  # Subpath of your site, e.g. /blog. For deploying to github pages, this should match your repo name
                            # Currently `gulp serve:dist` does not work with a baseurl specified. For this purpose,
                            # temporarily comment out this parameter
url: "https://carlorodriguez.github.io"  # Base hostname & protocol for your site

twitter_username: ''
github_username:  CarloRodriguez
disqus_shortname: carlorodriguezgithubio
google_analytics: UA-63351670-1

# Pagination
paginate: 5
paginate_path: "page:num"
excerpt_separator: <!--more-->

# Gems
gems:
  - jekyll-archives
  - jekyll-paginate

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# Archive settings
jekyll-archives:
  enabled: ['tags']
